import { useState } from 'react';
import { Copy, Check, ExternalLink } from 'lucide-react';

const WALinkGenerator = () => {
  const [phone, setPhone] = useState('');
    const [message, setMessage] = useState('');
      const [copied, setCopied] = useState(false);

        // Logik Bina Link
          const generateLink = () => {
              let cleanPhone = phone.replace(/\D/g, ''); // Buat nombor je
                  if (cleanPhone.startsWith('0')) {
                        cleanPhone = '6' + cleanPhone;
                            }
                                const encodedMessage = encodeURIComponent(message);
                                    return cleanPhone ? `https://wa.me/${cleanPhone}?text=${encodedMessage}` : '';
                                      };

                                        const fullLink = generateLink();

                                          const copyToClipboard = () => {
                                              if (!fullLink) return;
                                                  navigator.clipboard.writeText(fullLink);
                                                      setCopied(true);
                                                          setTimeout(() => setCopied(false), 2000);
                                                            };

                                                              return (
                                                                  <section id="tools" className="py-24 bg-[#0a0a0b] border-t border-white/5">
                                                                        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                                                                                <div className="text-center mb-12">
                                                                                          <h2 className="text-3xl md:text-5xl font-black text-white mb-4 uppercase italic tracking-tighter">
                                                                                                      WhatsApp <span className="text-yellow-500">Link Generator</span>
                                                                                                                </h2>
                                                                                                                          <p className="text-gray-400 font-medium text-sm">
                                                                                                                                      Tool percuma untuk bantu bisnes anda. Bina link WhatsApp dengan mesej automatik sekarang.
                                                                                                                                                </p>
                                                                                                                                                        </div>

                                                                                                                                                                <div className="bg-[#14151a] p-8 md:p-12 rounded-[2.5rem] border border-white/5 shadow-2xl">
                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                                                                                                                                                                      {/* Input Side */}
                                                                                                                                                                                                  <div className="space-y-6">
                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                <label className="block text-[10px] font-black uppercase tracking-widest text-yellow-500 mb-2">Nombor Telefon</label>
                                                                                                                                                                                                                                                <input 
                                                                                                                                                                                                                                                                  type="text" 
                                                                                                                                                                                                                                                                                    placeholder="Contoh: 01121281024"
                                                                                                                                                                                                                                                                                                      value={phone}
                                                                                                                                                                                                                                                                                                                        onChange={(e) => setPhone(e.target.value)}
                                                                                                                                                                                                                                                                                                                                          className="w-full bg-black/50 border border-white/10 rounded-2xl p-4 text-white outline-none focus:border-yellow-500 transition-all font-bold"
                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                                                                      <label className="block text-[10px] font-black uppercase tracking-widest text-yellow-500 mb-2">Mesej Automatik</label>
                                                                                                                                                                                                                                                                                                                                                                                                                      <textarea 
                                                                                                                                                                                                                                                                                                                                                                                                                                        rows={4}
                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Contoh: Salam Bos, saya berminat nak order..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={message}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setMessage(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full bg-black/50 border border-white/10 rounded-2xl p-4 text-white outline-none focus:border-yellow-500 transition-all text-sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {/* Result Side */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex flex-col justify-center bg-black/30 p-8 rounded-[2rem] border border-dashed border-white/10">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="text-[10px] font-black uppercase tracking-widest text-gray-500 mb-4 text-center">Hasil Link Anda</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-black/50 p-4 rounded-xl mb-6 break-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-xs font-mono text-yellow-500/70">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {fullLink || 'Sila masukkan nombor telefon...'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={copyToClipboard}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              disabled={!fullLink}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="flex items-center justify-center gap-2 bg-white text-black py-4 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-yellow-500 transition-all disabled:opacity-30"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {copied ? <Check size={14} /> : <Copy size={14} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {copied ? 'Copied!' : 'Copy Link'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      href={fullLink} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        target="_blank" 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className={`flex items-center justify-center gap-2 bg-yellow-500 text-black py-4 rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-white transition-all ${!fullLink && 'pointer-events-none opacity-30'}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Test Link <ExternalLink size={14} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-8 text-center text-gray-600 text-[9px] font-bold uppercase tracking-widest italic">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Developed by Azri Safwan Studio - No Login Required.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default WALinkGenerator;